name: Ejecutar Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar el script
        run: python array.py
